apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: label-operator
    appstudio.openshift.io/component: label-operator-gmy7
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: label-operator-gmy7
  namespace: gbenhaim-stonesoup-ocm-tenant
spec:
  url: https://github.com/gbenhaim/label-operator
