apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: label-operator-gmy7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: label-operator-gmy7
    app.kubernetes.io/part-of: label-operator
  name: label-operator-gmy7
  namespace: gbenhaim-stonesoup-ocm-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: label-operator-gmy7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: label-operator-gmy7
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:RFpUK-label-operator-gmy7
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
