apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: label-operator-gmy7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: label-operator-gmy7
    app.kubernetes.io/part-of: label-operator
  name: label-operator-gmy7
  namespace: gbenhaim-stonesoup-ocm-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: label-operator-gmy7
status:
  loadBalancer: {}
